package com.fb.platform.promotion.rule;

public enum RuleConfigEnum {
	
	CLIENT_LIST,
	CATEGORY_LIST,
	BRAND_LIST,
	MIN_ORDER_VALUE,
	FIXED_DISCOUNT_RS_OFF,
	DISCOUNT_PERCENTAGE,
	MAX_DISCOUNT_CEIL_IN_VALUE,
	PRODUCT_ID,
	PRODUCT_LIST,
	PRODUCT_DISCOUNT_RS_OFF,
	PRODUCT_DISCOUNTED_VALUE;

}
