/**
 * 
 */
package com.fb.platform.promotion.to;

import java.io.Serializable;

/**
 * @author vinayak
 *
 */
public enum ApplyCouponResponseStatusEnum implements Serializable {

	SUCCESS("SUCCESSFULLY APPLIED"),
	NO_SESSION("INVALID SESSION, PLEASE APPLY AGAIN OR LOGIN AGAIN AND TRY"),
	INVALID_COUPON_CODE("COUPON CODE USED IS INVALID"),
	COUPON_CODE_EXPIRED("COUPON CODE HAS EXPIRED"),
	USER_NOT_AUTHORIZED("YOU ARE NOT AN AUTHORIZED USER TO USE THIS"),
	NUMBER_OF_USES_EXCEEDED("NUMBER_OF_USES_EXCEEDED"),
	NOT_APPLICABLE("THIS COUPON IS NOT VALID FOR THIS USER"),
	LESS_ORDER_AMOUNT("DISCOUNT IS NOT VALID FOR THIS AMOUNT"),
	ALREADY_APPLIED_COUPON_ON_ORDER("COUPON HAS ALREADY BEEN APPLIED ON THE ORDER"),
	ALREADY_APPLIED_PROMOTION_ON_ORDER("PROMOTION HAS ALREADY BEEN APPLIED ON THE ORDER"),
	INTERNAL_ERROR("THERE WAS AN INTERNAL ERROR"),
	INVALID_CLIENT("THIS COUPON IS NOT VALID FOR THIS CLIENT"),
	CATEGORY_MISMATCH("THIS COUPON CANNOT BE APPLIED ON THIS CATEGORY"),
	BRAND_MISMATCH("THIS COUPON CANNOT BE APPLIED ON THIS BRAND"),
	INACTIVE_COUPON("SORRY, THIS COUPON IS NO LONGER ACTIVE"),
	TOTAL_MAX_USES_EXCEEDED("SORRY, MAX USES EXCEEDED"),
	TOTAL_MAX_USES_PER_USER_EXCEEDED("SORRY, MAX USES EXCEEDED"),
	TOTAL_MAX_AMOUNT_EXCEEDED("SORRY, MAX AMOUNT TO BE DISCOUNT EXCEEDED"),
	TOTAL_MAX_AMOUNT_PER_USER_EXCEEDED("SORRY, MAX AMOUNT TO BE DISCOUNT EXCEEDED"),
	LIMIT_SUCCESS("LIMIT_SUCCESS");

	private String status = null;
	
	private ApplyCouponResponseStatusEnum(String status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return this.status;
	}
}
