package com.fb.platform.promotion.to;

import java.io.Serializable;

public enum PromotionStatusEnum implements Serializable {

	SUCCESS("SUCCESS", "SUCCESSFULLY APPLIED"),
	INVALID_COUPON_CODE("INVALID_COUPON_CODE", "COUPON CODE USED IS INVALID"),
	INTERNAL_ERROR("INTERNAL_ERROR", "THERE WAS AN INTERNAL ERROR"),
	ALREADY_APPLIED_COUPON_ON_ORDER("ALREADY_APPLIED_COUPON_ON_ORDER", "COUPON HAS ALREADY BEEN APPLIED ON THE ORDER"),
	ALREADY_APPLIED_PROMOTION_ON_ORDER("ALREADY_APPLIED_PROMOTION_ON_ORDER", "PROMOTION HAS ALREADY BEEN APPLIED ON THE ORDER"),
	NO_APPLIED_COUPON_ON_ORDER("NO_APPLIED_COUPON_ON_ORDER", "NO APPLIED COUPON FOUND ON THE ORDER"),
	NO_APPLIED_PROMOTION_ON_ORDER("NO_APPLIED_PROMOTION_ON_ORDER", "NO APPLIED PROMOTION FOUND ON THE ORDER"),
	TOTAL_MAX_USES_EXCEEDED("TOTAL_MAX_USES_EXCEEDED", "SORRY, MAX USES EXCEEDED"),
	TOTAL_MAX_USES_PER_USER_EXCEEDED("TOTAL_MAX_USES_PER_USER_EXCEEDED", "SORRY, MAX USES EXCEEDED"),
	TOTAL_MAX_AMOUNT_EXCEEDED("TOTAL_MAX_AMOUNT_EXCEEDED", "SORRY, MAX AMOUNT TO BE DISCOUNT EXCEEDED"),
	TOTAL_MAX_AMOUNT_PER_USER_EXCEEDED("TOTAL_MAX_AMOUNT_PER_USER_EXCEEDED", "SORRY, MAX AMOUNT TO BE DISCOUNT EXCEEDED"),
	INACTIVE_COUPON("INACTIVE_COUPON", "SORRY, THIS COUPON IS NO LONGER ACTIVE"),	
	COUPON_CODE_EXPIRED("COUPON_CODE_EXPIRED", "COUPON CODE HAS EXPIRED"),
	
	USER_NOT_AUTHORIZED("USER_NOT_AUTHORIZED", "YOU ARE NOT AN AUTHORIZED USER TO USE THIS"),
	NUMBER_OF_USES_EXCEEDED("NUMBER_OF_USES_EXCEEDED", "NUMBER_OF_USES_EXCEEDED"),
	NOT_APPLICABLE("NOT_APPLICABLE", "THIS COUPON IS NOT VALID FOR THIS USER"),
	LESS_ORDER_AMOUNT("LESS_ORDER_AMOUNT", "DISCOUNT IS NOT VALID FOR THIS AMOUNT"),
	
	INVALID_CLIENT("INVALID_CLIENT", "THIS COUPON IS NOT VALID FOR THIS CLIENT"),
	CATEGORY_MISMATCH("CATEGORY_MISMATCH", "THIS COUPON CANNOT BE APPLIED ON THIS CATEGORY"),
	BRAND_MISMATCH("BRAND_MISMATCH", "THIS COUPON CANNOT BE APPLIED ON THIS BRAND"),
	
	
	LIMIT_SUCCESS("LIMIT_SUCCESS", "LIMIT_SUCCESS");

	private String status = null;
	private String message = null;
	
	private PromotionStatusEnum(String status, String message) {
		this.status = status;
		this.message = message;
	}

	@Override
	public String toString() {
		return this.status;
	}

	public String getMesage() {
		return message;
	}
}
