package com.fb.platform.sap.bapi.order.table;

public enum BapiOrderTable {
	
	RETURN,
	ORDER_TEXT,
	ORDER_PARTNERS,
	PARTNERS,
	ORDER_CCARD,
	ORDER_HEADER_IN,
	ORDER_HEADER_INX,
	ORDER_ITEMS_IN,
	ORDER_ITEM_IN,
	ORDER_ITEMS_INX,
	ORDER_ITEM_INX,
	RETURN_ITEM,
	ORDER_SCHEDULES_IN,
	SCHEDULE_LINES,
	ORDER_SCHEDULES_INX,
	SCHEDULE_LINESX,
	ORDER_CONDITIONS_IN,
	CONDITIONS_IN,
	ORDER_CONDITIONS_INX,
	CONDITIONS_INX,
	CHANGE_INDICATOR;
	
	@Override
	public String toString() {
		return this.name();
	}

}
