//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.03 at 06:45:40 PM GMT+05:30 
//


package com.fb.sap.idocs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idoc"
})
@XmlRootElement(name = "ZATGDELD")
public class DeliveryDeletedIDoc {

    @XmlElement(name = "IDOC", required = true)
    protected DeliveryDeletedIDoc.IDOC idoc;

    /**
     * Gets the value of the idoc property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryDeletedIDoc.IDOC }
     *     
     */
    public DeliveryDeletedIDoc.IDOC getIDOC() {
        return idoc;
    }

    /**
     * Sets the value of the idoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryDeletedIDoc.IDOC }
     *     
     */
    public void setIDOC(DeliveryDeletedIDoc.IDOC value) {
        this.idoc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EDI_DC40">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TABNAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MANDT" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="3"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DOCNUM" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="16"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DOCREL" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="STATUS" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DIRECT">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="1"/>
     *                         &lt;enumeration value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="OUTMOD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="EXPRSS" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TEST" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="IDOCTYP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CIMTYP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="MESTYP" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="30"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="MESCOD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="3"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="MESFCT" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="3"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="STD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="STDVRS" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="6"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="STDMES" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="6"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SNDPOR">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SNDPRT">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SNDPFC" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SNDPRN">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SNDSAD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="21"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SNDLAD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="70"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RCVPOR">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RCVPRT" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RCVPFC" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RCVPRN">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RCVSAD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="21"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RCVLAD" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="70"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CREDAT" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="8"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CRETIM" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="6"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="REFINT" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="14"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="REFGRP" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="14"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="REFMES" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="14"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ARCKEY" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="70"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SERIAL" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="SEGMENT" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ZATGSOH" maxOccurs="4999" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="VBELN" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ZATGSOD" maxOccurs="4999" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="VBELN" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="POSNR" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="6"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DELUSER" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="12"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DELTCODE" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="20"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DELDATE" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="8"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DELTIME" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="6"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="SEGMENT" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="1"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="SEGMENT" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="BEGIN" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "edidc40",
        "zatgsoh"
    })
    public static class IDOC {

        @XmlElement(name = "EDI_DC40", required = true)
        protected DeliveryDeletedIDoc.IDOC.EDIDC40 edidc40;
        @XmlElement(name = "ZATGSOH")
        protected List<DeliveryDeletedIDoc.IDOC.ZATGSOH> zatgsoh;
        @XmlAttribute(name = "BEGIN", required = true)
        protected String begin;

        /**
         * Gets the value of the edidc40 property.
         * 
         * @return
         *     possible object is
         *     {@link DeliveryDeletedIDoc.IDOC.EDIDC40 }
         *     
         */
        public DeliveryDeletedIDoc.IDOC.EDIDC40 getEDIDC40() {
            return edidc40;
        }

        /**
         * Sets the value of the edidc40 property.
         * 
         * @param value
         *     allowed object is
         *     {@link DeliveryDeletedIDoc.IDOC.EDIDC40 }
         *     
         */
        public void setEDIDC40(DeliveryDeletedIDoc.IDOC.EDIDC40 value) {
            this.edidc40 = value;
        }

        /**
         * Gets the value of the zatgsoh property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zatgsoh property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getZATGSOH().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeliveryDeletedIDoc.IDOC.ZATGSOH }
         * 
         * 
         */
        public List<DeliveryDeletedIDoc.IDOC.ZATGSOH> getZATGSOH() {
            if (zatgsoh == null) {
                zatgsoh = new ArrayList<DeliveryDeletedIDoc.IDOC.ZATGSOH>();
            }
            return this.zatgsoh;
        }

        /**
         * Gets the value of the begin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBEGIN() {
            return begin;
        }

        /**
         * Sets the value of the begin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBEGIN(String value) {
            this.begin = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TABNAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MANDT" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="3"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DOCNUM" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="16"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DOCREL" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="STATUS" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DIRECT">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="1"/>
         *               &lt;enumeration value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="OUTMOD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="EXPRSS" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TEST" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="IDOCTYP" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CIMTYP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="MESTYP" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="30"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="MESCOD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="3"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="MESFCT" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="3"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="STD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="STDVRS" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="6"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="STDMES" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="6"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SNDPOR">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SNDPRT">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SNDPFC" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SNDPRN">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SNDSAD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="21"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SNDLAD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="70"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RCVPOR">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RCVPRT" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RCVPFC" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RCVPRN">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RCVSAD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="21"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RCVLAD" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="70"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CREDAT" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="8"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CRETIM" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="6"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="REFINT" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="14"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="REFGRP" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="14"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="REFMES" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="14"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ARCKEY" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="70"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SERIAL" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="20"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="SEGMENT" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tabnam",
            "mandt",
            "docnum",
            "docrel",
            "status",
            "direct",
            "outmod",
            "exprss",
            "test",
            "idoctyp",
            "cimtyp",
            "mestyp",
            "mescod",
            "mesfct",
            "std",
            "stdvrs",
            "stdmes",
            "sndpor",
            "sndprt",
            "sndpfc",
            "sndprn",
            "sndsad",
            "sndlad",
            "rcvpor",
            "rcvprt",
            "rcvpfc",
            "rcvprn",
            "rcvsad",
            "rcvlad",
            "credat",
            "cretim",
            "refint",
            "refgrp",
            "refmes",
            "arckey",
            "serial"
        })
        public static class EDIDC40 {

            @XmlElement(name = "TABNAM", required = true)
            protected String tabnam;
            @XmlElement(name = "MANDT")
            protected String mandt;
            @XmlElement(name = "DOCNUM")
            protected String docnum;
            @XmlElement(name = "DOCREL")
            protected String docrel;
            @XmlElement(name = "STATUS")
            protected String status;
            @XmlElement(name = "DIRECT", required = true)
            protected String direct;
            @XmlElement(name = "OUTMOD")
            protected String outmod;
            @XmlElement(name = "EXPRSS")
            protected String exprss;
            @XmlElement(name = "TEST")
            protected String test;
            @XmlElement(name = "IDOCTYP", required = true)
            protected String idoctyp;
            @XmlElement(name = "CIMTYP")
            protected String cimtyp;
            @XmlElement(name = "MESTYP")
            protected String mestyp;
            @XmlElement(name = "MESCOD")
            protected String mescod;
            @XmlElement(name = "MESFCT")
            protected String mesfct;
            @XmlElement(name = "STD")
            protected String std;
            @XmlElement(name = "STDVRS")
            protected String stdvrs;
            @XmlElement(name = "STDMES")
            protected String stdmes;
            @XmlElement(name = "SNDPOR", required = true)
            protected String sndpor;
            @XmlElement(name = "SNDPRT", required = true)
            protected String sndprt;
            @XmlElement(name = "SNDPFC")
            protected String sndpfc;
            @XmlElement(name = "SNDPRN", required = true)
            protected String sndprn;
            @XmlElement(name = "SNDSAD")
            protected String sndsad;
            @XmlElement(name = "SNDLAD")
            protected String sndlad;
            @XmlElement(name = "RCVPOR", required = true)
            protected String rcvpor;
            @XmlElement(name = "RCVPRT")
            protected String rcvprt;
            @XmlElement(name = "RCVPFC")
            protected String rcvpfc;
            @XmlElement(name = "RCVPRN", required = true)
            protected String rcvprn;
            @XmlElement(name = "RCVSAD")
            protected String rcvsad;
            @XmlElement(name = "RCVLAD")
            protected String rcvlad;
            @XmlElement(name = "CREDAT")
            protected String credat;
            @XmlElement(name = "CRETIM")
            protected String cretim;
            @XmlElement(name = "REFINT")
            protected String refint;
            @XmlElement(name = "REFGRP")
            protected String refgrp;
            @XmlElement(name = "REFMES")
            protected String refmes;
            @XmlElement(name = "ARCKEY")
            protected String arckey;
            @XmlElement(name = "SERIAL")
            protected String serial;
            @XmlAttribute(name = "SEGMENT", required = true)
            protected String segment;

            /**
             * Gets the value of the tabnam property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTABNAM() {
                return tabnam;
            }

            /**
             * Sets the value of the tabnam property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTABNAM(String value) {
                this.tabnam = value;
            }

            /**
             * Gets the value of the mandt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMANDT() {
                return mandt;
            }

            /**
             * Sets the value of the mandt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMANDT(String value) {
                this.mandt = value;
            }

            /**
             * Gets the value of the docnum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDOCNUM() {
                return docnum;
            }

            /**
             * Sets the value of the docnum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDOCNUM(String value) {
                this.docnum = value;
            }

            /**
             * Gets the value of the docrel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDOCREL() {
                return docrel;
            }

            /**
             * Sets the value of the docrel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDOCREL(String value) {
                this.docrel = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTATUS() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTATUS(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the direct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDIRECT() {
                return direct;
            }

            /**
             * Sets the value of the direct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDIRECT(String value) {
                this.direct = value;
            }

            /**
             * Gets the value of the outmod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOUTMOD() {
                return outmod;
            }

            /**
             * Sets the value of the outmod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOUTMOD(String value) {
                this.outmod = value;
            }

            /**
             * Gets the value of the exprss property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEXPRSS() {
                return exprss;
            }

            /**
             * Sets the value of the exprss property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEXPRSS(String value) {
                this.exprss = value;
            }

            /**
             * Gets the value of the test property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTEST() {
                return test;
            }

            /**
             * Sets the value of the test property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTEST(String value) {
                this.test = value;
            }

            /**
             * Gets the value of the idoctyp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIDOCTYP() {
                return idoctyp;
            }

            /**
             * Sets the value of the idoctyp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIDOCTYP(String value) {
                this.idoctyp = value;
            }

            /**
             * Gets the value of the cimtyp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCIMTYP() {
                return cimtyp;
            }

            /**
             * Sets the value of the cimtyp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCIMTYP(String value) {
                this.cimtyp = value;
            }

            /**
             * Gets the value of the mestyp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMESTYP() {
                return mestyp;
            }

            /**
             * Sets the value of the mestyp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMESTYP(String value) {
                this.mestyp = value;
            }

            /**
             * Gets the value of the mescod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMESCOD() {
                return mescod;
            }

            /**
             * Sets the value of the mescod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMESCOD(String value) {
                this.mescod = value;
            }

            /**
             * Gets the value of the mesfct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMESFCT() {
                return mesfct;
            }

            /**
             * Sets the value of the mesfct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMESFCT(String value) {
                this.mesfct = value;
            }

            /**
             * Gets the value of the std property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTD() {
                return std;
            }

            /**
             * Sets the value of the std property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTD(String value) {
                this.std = value;
            }

            /**
             * Gets the value of the stdvrs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTDVRS() {
                return stdvrs;
            }

            /**
             * Sets the value of the stdvrs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTDVRS(String value) {
                this.stdvrs = value;
            }

            /**
             * Gets the value of the stdmes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTDMES() {
                return stdmes;
            }

            /**
             * Sets the value of the stdmes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTDMES(String value) {
                this.stdmes = value;
            }

            /**
             * Gets the value of the sndpor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSNDPOR() {
                return sndpor;
            }

            /**
             * Sets the value of the sndpor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSNDPOR(String value) {
                this.sndpor = value;
            }

            /**
             * Gets the value of the sndprt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSNDPRT() {
                return sndprt;
            }

            /**
             * Sets the value of the sndprt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSNDPRT(String value) {
                this.sndprt = value;
            }

            /**
             * Gets the value of the sndpfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSNDPFC() {
                return sndpfc;
            }

            /**
             * Sets the value of the sndpfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSNDPFC(String value) {
                this.sndpfc = value;
            }

            /**
             * Gets the value of the sndprn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSNDPRN() {
                return sndprn;
            }

            /**
             * Sets the value of the sndprn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSNDPRN(String value) {
                this.sndprn = value;
            }

            /**
             * Gets the value of the sndsad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSNDSAD() {
                return sndsad;
            }

            /**
             * Sets the value of the sndsad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSNDSAD(String value) {
                this.sndsad = value;
            }

            /**
             * Gets the value of the sndlad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSNDLAD() {
                return sndlad;
            }

            /**
             * Sets the value of the sndlad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSNDLAD(String value) {
                this.sndlad = value;
            }

            /**
             * Gets the value of the rcvpor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRCVPOR() {
                return rcvpor;
            }

            /**
             * Sets the value of the rcvpor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRCVPOR(String value) {
                this.rcvpor = value;
            }

            /**
             * Gets the value of the rcvprt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRCVPRT() {
                return rcvprt;
            }

            /**
             * Sets the value of the rcvprt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRCVPRT(String value) {
                this.rcvprt = value;
            }

            /**
             * Gets the value of the rcvpfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRCVPFC() {
                return rcvpfc;
            }

            /**
             * Sets the value of the rcvpfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRCVPFC(String value) {
                this.rcvpfc = value;
            }

            /**
             * Gets the value of the rcvprn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRCVPRN() {
                return rcvprn;
            }

            /**
             * Sets the value of the rcvprn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRCVPRN(String value) {
                this.rcvprn = value;
            }

            /**
             * Gets the value of the rcvsad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRCVSAD() {
                return rcvsad;
            }

            /**
             * Sets the value of the rcvsad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRCVSAD(String value) {
                this.rcvsad = value;
            }

            /**
             * Gets the value of the rcvlad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRCVLAD() {
                return rcvlad;
            }

            /**
             * Sets the value of the rcvlad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRCVLAD(String value) {
                this.rcvlad = value;
            }

            /**
             * Gets the value of the credat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCREDAT() {
                return credat;
            }

            /**
             * Sets the value of the credat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCREDAT(String value) {
                this.credat = value;
            }

            /**
             * Gets the value of the cretim property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCRETIM() {
                return cretim;
            }

            /**
             * Sets the value of the cretim property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCRETIM(String value) {
                this.cretim = value;
            }

            /**
             * Gets the value of the refint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREFINT() {
                return refint;
            }

            /**
             * Sets the value of the refint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREFINT(String value) {
                this.refint = value;
            }

            /**
             * Gets the value of the refgrp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREFGRP() {
                return refgrp;
            }

            /**
             * Sets the value of the refgrp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREFGRP(String value) {
                this.refgrp = value;
            }

            /**
             * Gets the value of the refmes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREFMES() {
                return refmes;
            }

            /**
             * Sets the value of the refmes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREFMES(String value) {
                this.refmes = value;
            }

            /**
             * Gets the value of the arckey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getARCKEY() {
                return arckey;
            }

            /**
             * Sets the value of the arckey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setARCKEY(String value) {
                this.arckey = value;
            }

            /**
             * Gets the value of the serial property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSERIAL() {
                return serial;
            }

            /**
             * Sets the value of the serial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSERIAL(String value) {
                this.serial = value;
            }

            /**
             * Gets the value of the segment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSEGMENT() {
                return segment;
            }

            /**
             * Sets the value of the segment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSEGMENT(String value) {
                this.segment = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="VBELN" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ZATGSOD" maxOccurs="4999" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="VBELN" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="POSNR" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="6"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DELUSER" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="12"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DELTCODE" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="20"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DELDATE" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="8"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DELTIME" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="6"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="SEGMENT" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="1"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="SEGMENT" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vbeln",
            "zatgsod"
        })
        public static class ZATGSOH {

            @XmlElement(name = "VBELN")
            protected String vbeln;
            @XmlElement(name = "ZATGSOD")
            protected List<DeliveryDeletedIDoc.IDOC.ZATGSOH.ZATGSOD> zatgsod;
            @XmlAttribute(name = "SEGMENT", required = true)
            protected String segment;

            /**
             * Gets the value of the vbeln property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVBELN() {
                return vbeln;
            }

            /**
             * Sets the value of the vbeln property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVBELN(String value) {
                this.vbeln = value;
            }

            /**
             * Gets the value of the zatgsod property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the zatgsod property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getZATGSOD().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DeliveryDeletedIDoc.IDOC.ZATGSOH.ZATGSOD }
             * 
             * 
             */
            public List<DeliveryDeletedIDoc.IDOC.ZATGSOH.ZATGSOD> getZATGSOD() {
                if (zatgsod == null) {
                    zatgsod = new ArrayList<DeliveryDeletedIDoc.IDOC.ZATGSOH.ZATGSOD>();
                }
                return this.zatgsod;
            }

            /**
             * Gets the value of the segment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSEGMENT() {
                return segment;
            }

            /**
             * Sets the value of the segment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSEGMENT(String value) {
                this.segment = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="VBELN" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="POSNR" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="6"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DELUSER" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="12"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DELTCODE" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="20"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DELDATE" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="8"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DELTIME" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="6"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="SEGMENT" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="1"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "vbeln",
                "posnr",
                "deluser",
                "deltcode",
                "deldate",
                "deltime"
            })
            public static class ZATGSOD {

                @XmlElement(name = "VBELN")
                protected String vbeln;
                @XmlElement(name = "POSNR")
                protected String posnr;
                @XmlElement(name = "DELUSER")
                protected String deluser;
                @XmlElement(name = "DELTCODE")
                protected String deltcode;
                @XmlElement(name = "DELDATE")
                protected String deldate;
                @XmlElement(name = "DELTIME")
                protected String deltime;
                @XmlAttribute(name = "SEGMENT", required = true)
                protected String segment;

                /**
                 * Gets the value of the vbeln property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVBELN() {
                    return vbeln;
                }

                /**
                 * Sets the value of the vbeln property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVBELN(String value) {
                    this.vbeln = value;
                }

                /**
                 * Gets the value of the posnr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPOSNR() {
                    return posnr;
                }

                /**
                 * Sets the value of the posnr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPOSNR(String value) {
                    this.posnr = value;
                }

                /**
                 * Gets the value of the deluser property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELUSER() {
                    return deluser;
                }

                /**
                 * Sets the value of the deluser property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELUSER(String value) {
                    this.deluser = value;
                }

                /**
                 * Gets the value of the deltcode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELTCODE() {
                    return deltcode;
                }

                /**
                 * Sets the value of the deltcode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELTCODE(String value) {
                    this.deltcode = value;
                }

                /**
                 * Gets the value of the deldate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELDATE() {
                    return deldate;
                }

                /**
                 * Sets the value of the deldate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELDATE(String value) {
                    this.deldate = value;
                }

                /**
                 * Gets the value of the deltime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELTIME() {
                    return deltime;
                }

                /**
                 * Sets the value of the deltime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELTIME(String value) {
                    this.deltime = value;
                }

                /**
                 * Gets the value of the segment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSEGMENT() {
                    return segment;
                }

                /**
                 * Sets the value of the segment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSEGMENT(String value) {
                    this.segment = value;
                }

            }

        }

    }

}
