//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:58:53 PM GMT+05:30 
//


package com.fb.sap.idocs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeliveryDeletedIDoc.IDOC.ZATGSOH }
     * 
     */
    public DeliveryDeletedIDoc.IDOC.ZATGSOH createZATGDELDIDOCZATGSOH() {
        return new DeliveryDeletedIDoc.IDOC.ZATGSOH();
    }

    /**
     * Create an instance of {@link ZATGDELD.IDOC.EDIDC40 }
     * 
     */
    public DeliveryDeletedIDoc.IDOC.EDIDC40 createZATGDELDIDOCEDIDC40() {
        return new DeliveryDeletedIDoc.IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link ZATGDELD.IDOC }
     * 
     */
    public DeliveryDeletedIDoc.IDOC createZATGDELDIDOC() {
        return new DeliveryDeletedIDoc.IDOC();
    }

    /**
     * Create an instance of {@link ZATGDELD.IDOC.ZATGSOH.ZATGSOD }
     * 
     */
    public DeliveryDeletedIDoc.IDOC.ZATGSOH.ZATGSOD createZATGDELDIDOCZATGSOHZATGSOD() {
        return new DeliveryDeletedIDoc.IDOC.ZATGSOH.ZATGSOD();
    }

    /**
     * Create an instance of {@link ZATGDELD }
     * 
     */
    public DeliveryDeletedIDoc createZATGDELD() {
        return new DeliveryDeletedIDoc();
    }
    
    /**
     * Create an instance of {@link generated.ZATGFLOW.IDOC.ZATGFLOW }
     * 
     */
    public OrderIDoc.IDOC.ZATGFLOW createZATGFLOWIDOCZATGFLOW() {
        return new OrderIDoc.IDOC.ZATGFLOW();
    }

    /**
     * Create an instance of {@link generated.ZATGFLOW }
     * 
     */
    public OrderIDoc createZATGFLOW() {
        return new OrderIDoc();
    }

    /**
     * Create an instance of {@link generated.ZATGFLOW.IDOC }
     * 
     */
    public OrderIDoc.IDOC createZATGFLOWIDOC() {
        return new OrderIDoc.IDOC();
    }

    /**
     * Create an instance of {@link generated.ZATGFLOW.IDOC.EDIDC40 }
     * 
     */
    public OrderIDoc.IDOC.EDIDC40 createZATGFLOWIDOCEDIDC40() {
        return new OrderIDoc.IDOC.EDIDC40();
    }

}
