//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.03 at 06:47:32 PM GMT+05:30 
//

package com.fb.sap.idocs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "idoc" })
@XmlRootElement(name = "ZATGFLOW")
public class OrderIDoc {

	@XmlElement(name = "IDOC", required = true)
	protected OrderIDoc.IDOC idoc;

	/**
	 * Gets the value of the idoc property.
	 * 
	 * @return possible object is {@link OrderIDoc.IDOC }
	 * 
	 */
	public OrderIDoc.IDOC getIDOC() {
		return idoc;
	}

	/**
	 * Sets the value of the idoc property.
	 * 
	 * @param value
	 *            allowed object is {@link OrderIDoc.IDOC }
	 * 
	 */
	public void setIDOC(OrderIDoc.IDOC value) {
		this.idoc = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "edidc40", "zatgflow" })
	public static class IDOC {

		@XmlElement(name = "EDI_DC40", required = true)
		protected OrderIDoc.IDOC.EDIDC40 edidc40;
		@XmlElement(name = "ZATGFLOW")
		protected List<OrderIDoc.IDOC.ZATGFLOW> zatgflow;
		@XmlAttribute(name = "BEGIN", required = true)
		protected String begin;

		/**
		 * Gets the value of the edidc40 property.
		 * 
		 * @return possible object is {@link OrderIDoc.IDOC.EDIDC40 }
		 * 
		 */
		public OrderIDoc.IDOC.EDIDC40 getEDIDC40() {
			return edidc40;
		}

		/**
		 * Sets the value of the edidc40 property.
		 * 
		 * @param value
		 *            allowed object is {@link OrderIDoc.IDOC.EDIDC40 }
		 * 
		 */
		public void setEDIDC40(OrderIDoc.IDOC.EDIDC40 value) {
			this.edidc40 = value;
		}

		/**
		 * Gets the value of the zatgflow property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the zatgflow property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getZATGFLOW().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link OrderIDoc.IDOC.ZATGFLOW }
		 * 
		 * 
		 */
		public List<OrderIDoc.IDOC.ZATGFLOW> getZATGFLOW() {
			if (zatgflow == null) {
				zatgflow = new ArrayList<OrderIDoc.IDOC.ZATGFLOW>();
			}
			return this.zatgflow;
		}

		/**
		 * Gets the value of the begin property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBEGIN() {
			return begin;
		}

		/**
		 * Sets the value of the begin property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBEGIN(String value) {
			this.begin = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "tabnam", "mandt", "docnum",
				"docrel", "status", "direct", "outmod", "exprss", "test",
				"idoctyp", "cimtyp", "mestyp", "mescod", "mesfct", "std",
				"stdvrs", "stdmes", "sndpor", "sndprt", "sndpfc", "sndprn",
				"sndsad", "sndlad", "rcvpor", "rcvprt", "rcvpfc", "rcvprn",
				"rcvsad", "rcvlad", "credat", "cretim", "refint", "refgrp",
				"refmes", "arckey", "serial" })
		public static class EDIDC40 {

			@XmlElement(name = "TABNAM", required = true)
			protected String tabnam;
			@XmlElement(name = "MANDT")
			protected String mandt;
			@XmlElement(name = "DOCNUM")
			protected String docnum;
			@XmlElement(name = "DOCREL")
			protected String docrel;
			@XmlElement(name = "STATUS")
			protected String status;
			@XmlElement(name = "DIRECT", required = true)
			protected String direct;
			@XmlElement(name = "OUTMOD")
			protected String outmod;
			@XmlElement(name = "EXPRSS")
			protected String exprss;
			@XmlElement(name = "TEST")
			protected String test;
			@XmlElement(name = "IDOCTYP", required = true)
			protected String idoctyp;
			@XmlElement(name = "CIMTYP")
			protected String cimtyp;
			@XmlElement(name = "MESTYP")
			protected String mestyp;
			@XmlElement(name = "MESCOD")
			protected String mescod;
			@XmlElement(name = "MESFCT")
			protected String mesfct;
			@XmlElement(name = "STD")
			protected String std;
			@XmlElement(name = "STDVRS")
			protected String stdvrs;
			@XmlElement(name = "STDMES")
			protected String stdmes;
			@XmlElement(name = "SNDPOR", required = true)
			protected String sndpor;
			@XmlElement(name = "SNDPRT", required = true)
			protected String sndprt;
			@XmlElement(name = "SNDPFC")
			protected String sndpfc;
			@XmlElement(name = "SNDPRN", required = true)
			protected String sndprn;
			@XmlElement(name = "SNDSAD")
			protected String sndsad;
			@XmlElement(name = "SNDLAD")
			protected String sndlad;
			@XmlElement(name = "RCVPOR", required = true)
			protected String rcvpor;
			@XmlElement(name = "RCVPRT")
			protected String rcvprt;
			@XmlElement(name = "RCVPFC")
			protected String rcvpfc;
			@XmlElement(name = "RCVPRN", required = true)
			protected String rcvprn;
			@XmlElement(name = "RCVSAD")
			protected String rcvsad;
			@XmlElement(name = "RCVLAD")
			protected String rcvlad;
			@XmlElement(name = "CREDAT")
			protected String credat;
			@XmlElement(name = "CRETIM")
			protected String cretim;
			@XmlElement(name = "REFINT")
			protected String refint;
			@XmlElement(name = "REFGRP")
			protected String refgrp;
			@XmlElement(name = "REFMES")
			protected String refmes;
			@XmlElement(name = "ARCKEY")
			protected String arckey;
			@XmlElement(name = "SERIAL")
			protected String serial;
			@XmlAttribute(name = "SEGMENT", required = true)
			protected String segment;

			/**
			 * Gets the value of the tabnam property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getTABNAM() {
				return tabnam;
			}

			/**
			 * Sets the value of the tabnam property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setTABNAM(String value) {
				this.tabnam = value;
			}

			/**
			 * Gets the value of the mandt property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMANDT() {
				return mandt;
			}

			/**
			 * Sets the value of the mandt property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMANDT(String value) {
				this.mandt = value;
			}

			/**
			 * Gets the value of the docnum property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDOCNUM() {
				return docnum;
			}

			/**
			 * Sets the value of the docnum property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDOCNUM(String value) {
				this.docnum = value;
			}

			/**
			 * Gets the value of the docrel property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDOCREL() {
				return docrel;
			}

			/**
			 * Sets the value of the docrel property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDOCREL(String value) {
				this.docrel = value;
			}

			/**
			 * Gets the value of the status property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSTATUS() {
				return status;
			}

			/**
			 * Sets the value of the status property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSTATUS(String value) {
				this.status = value;
			}

			/**
			 * Gets the value of the direct property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDIRECT() {
				return direct;
			}

			/**
			 * Sets the value of the direct property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDIRECT(String value) {
				this.direct = value;
			}

			/**
			 * Gets the value of the outmod property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOUTMOD() {
				return outmod;
			}

			/**
			 * Sets the value of the outmod property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOUTMOD(String value) {
				this.outmod = value;
			}

			/**
			 * Gets the value of the exprss property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getEXPRSS() {
				return exprss;
			}

			/**
			 * Sets the value of the exprss property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setEXPRSS(String value) {
				this.exprss = value;
			}

			/**
			 * Gets the value of the test property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getTEST() {
				return test;
			}

			/**
			 * Sets the value of the test property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setTEST(String value) {
				this.test = value;
			}

			/**
			 * Gets the value of the idoctyp property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getIDOCTYP() {
				return idoctyp;
			}

			/**
			 * Sets the value of the idoctyp property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setIDOCTYP(String value) {
				this.idoctyp = value;
			}

			/**
			 * Gets the value of the cimtyp property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCIMTYP() {
				return cimtyp;
			}

			/**
			 * Sets the value of the cimtyp property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCIMTYP(String value) {
				this.cimtyp = value;
			}

			/**
			 * Gets the value of the mestyp property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMESTYP() {
				return mestyp;
			}

			/**
			 * Sets the value of the mestyp property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMESTYP(String value) {
				this.mestyp = value;
			}

			/**
			 * Gets the value of the mescod property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMESCOD() {
				return mescod;
			}

			/**
			 * Sets the value of the mescod property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMESCOD(String value) {
				this.mescod = value;
			}

			/**
			 * Gets the value of the mesfct property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMESFCT() {
				return mesfct;
			}

			/**
			 * Sets the value of the mesfct property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMESFCT(String value) {
				this.mesfct = value;
			}

			/**
			 * Gets the value of the std property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSTD() {
				return std;
			}

			/**
			 * Sets the value of the std property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSTD(String value) {
				this.std = value;
			}

			/**
			 * Gets the value of the stdvrs property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSTDVRS() {
				return stdvrs;
			}

			/**
			 * Sets the value of the stdvrs property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSTDVRS(String value) {
				this.stdvrs = value;
			}

			/**
			 * Gets the value of the stdmes property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSTDMES() {
				return stdmes;
			}

			/**
			 * Sets the value of the stdmes property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSTDMES(String value) {
				this.stdmes = value;
			}

			/**
			 * Gets the value of the sndpor property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSNDPOR() {
				return sndpor;
			}

			/**
			 * Sets the value of the sndpor property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSNDPOR(String value) {
				this.sndpor = value;
			}

			/**
			 * Gets the value of the sndprt property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSNDPRT() {
				return sndprt;
			}

			/**
			 * Sets the value of the sndprt property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSNDPRT(String value) {
				this.sndprt = value;
			}

			/**
			 * Gets the value of the sndpfc property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSNDPFC() {
				return sndpfc;
			}

			/**
			 * Sets the value of the sndpfc property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSNDPFC(String value) {
				this.sndpfc = value;
			}

			/**
			 * Gets the value of the sndprn property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSNDPRN() {
				return sndprn;
			}

			/**
			 * Sets the value of the sndprn property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSNDPRN(String value) {
				this.sndprn = value;
			}

			/**
			 * Gets the value of the sndsad property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSNDSAD() {
				return sndsad;
			}

			/**
			 * Sets the value of the sndsad property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSNDSAD(String value) {
				this.sndsad = value;
			}

			/**
			 * Gets the value of the sndlad property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSNDLAD() {
				return sndlad;
			}

			/**
			 * Sets the value of the sndlad property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSNDLAD(String value) {
				this.sndlad = value;
			}

			/**
			 * Gets the value of the rcvpor property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRCVPOR() {
				return rcvpor;
			}

			/**
			 * Sets the value of the rcvpor property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRCVPOR(String value) {
				this.rcvpor = value;
			}

			/**
			 * Gets the value of the rcvprt property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRCVPRT() {
				return rcvprt;
			}

			/**
			 * Sets the value of the rcvprt property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRCVPRT(String value) {
				this.rcvprt = value;
			}

			/**
			 * Gets the value of the rcvpfc property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRCVPFC() {
				return rcvpfc;
			}

			/**
			 * Sets the value of the rcvpfc property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRCVPFC(String value) {
				this.rcvpfc = value;
			}

			/**
			 * Gets the value of the rcvprn property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRCVPRN() {
				return rcvprn;
			}

			/**
			 * Sets the value of the rcvprn property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRCVPRN(String value) {
				this.rcvprn = value;
			}

			/**
			 * Gets the value of the rcvsad property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRCVSAD() {
				return rcvsad;
			}

			/**
			 * Sets the value of the rcvsad property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRCVSAD(String value) {
				this.rcvsad = value;
			}

			/**
			 * Gets the value of the rcvlad property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRCVLAD() {
				return rcvlad;
			}

			/**
			 * Sets the value of the rcvlad property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRCVLAD(String value) {
				this.rcvlad = value;
			}

			/**
			 * Gets the value of the credat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCREDAT() {
				return credat;
			}

			/**
			 * Sets the value of the credat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCREDAT(String value) {
				this.credat = value;
			}

			/**
			 * Gets the value of the cretim property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCRETIM() {
				return cretim;
			}

			/**
			 * Sets the value of the cretim property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCRETIM(String value) {
				this.cretim = value;
			}

			/**
			 * Gets the value of the refint property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREFINT() {
				return refint;
			}

			/**
			 * Sets the value of the refint property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREFINT(String value) {
				this.refint = value;
			}

			/**
			 * Gets the value of the refgrp property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREFGRP() {
				return refgrp;
			}

			/**
			 * Sets the value of the refgrp property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREFGRP(String value) {
				this.refgrp = value;
			}

			/**
			 * Gets the value of the refmes property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREFMES() {
				return refmes;
			}

			/**
			 * Sets the value of the refmes property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREFMES(String value) {
				this.refmes = value;
			}

			/**
			 * Gets the value of the arckey property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getARCKEY() {
				return arckey;
			}

			/**
			 * Sets the value of the arckey property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setARCKEY(String value) {
				this.arckey = value;
			}

			/**
			 * Gets the value of the serial property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSERIAL() {
				return serial;
			}

			/**
			 * Sets the value of the serial property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSERIAL(String value) {
				this.serial = value;
			}

			/**
			 * Gets the value of the segment property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSEGMENT() {
				return segment;
			}

			/**
			 * Sets the value of the segment property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSEGMENT(String value) {
				this.segment = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "mandt", "sovbeln", "soposnr",
				"revbeln", "reposnr", "suvbeln", "suposnr", "vbelv", "posnv",
				"vbeln", "posnn", "vbtypn", "rfmng", "meins", "rfwrt", "waers",
				"bwart", "matnr", "erzet", "erdat", "taqui", "plmin", "vbtypv",
				"aedat", "fktyp", "brgew", "gewei", "volum", "voleh", "gbstk",
				"abstk", "lfgsk", "lfstk", "wbstk", "fkstk", "fksak", "buchk",
				"kostk", "lvstk", "pkstk", "cmgst", "fsstk", "lsstk", "spstg",
				"completeness", "material", "site", "reasoncode", "ordreason",
				"rejreason", "audat", "auart", "lifsk", "lifsp", "zmeins",
				"lgort", "pstyv", "lfart", "erdatdel", "ernamdel", "wadatpgi",
				"wadatpgr", "fkdat", "fkart", "netwr", "ordstat", "lspnor",
				"lspname", "lspupddescr" })
		public static class ZATGFLOW {

			@XmlElement(name = "MANDT")
			protected String mandt;
			@XmlElement(name = "SO_VBELN")
			protected String sovbeln;
			@XmlElement(name = "SO_POSNR")
			protected String soposnr;
			@XmlElement(name = "RE_VBELN")
			protected String revbeln;
			@XmlElement(name = "RE_POSNR")
			protected String reposnr;
			@XmlElement(name = "SU_VBELN")
			protected String suvbeln;
			@XmlElement(name = "SU_POSNR")
			protected String suposnr;
			@XmlElement(name = "VBELV")
			protected String vbelv;
			@XmlElement(name = "POSNV")
			protected String posnv;
			@XmlElement(name = "VBELN")
			protected String vbeln;
			@XmlElement(name = "POSNN")
			protected String posnn;
			@XmlElement(name = "VBTYP_N")
			protected String vbtypn;
			@XmlElement(name = "RFMNG")
			protected String rfmng;
			@XmlElement(name = "MEINS")
			protected String meins;
			@XmlElement(name = "RFWRT")
			protected String rfwrt;
			@XmlElement(name = "WAERS")
			protected String waers;
			@XmlElement(name = "BWART")
			protected String bwart;
			@XmlElement(name = "MATNR")
			protected String matnr;
			@XmlElement(name = "ERZET")
			protected String erzet;
			@XmlElement(name = "ERDAT")
			protected String erdat;
			@XmlElement(name = "TAQUI")
			protected String taqui;
			@XmlElement(name = "PLMIN")
			protected String plmin;
			@XmlElement(name = "VBTYP_V")
			protected String vbtypv;
			@XmlElement(name = "AEDAT")
			protected String aedat;
			@XmlElement(name = "FKTYP")
			protected String fktyp;
			@XmlElement(name = "BRGEW")
			protected String brgew;
			@XmlElement(name = "GEWEI")
			protected String gewei;
			@XmlElement(name = "VOLUM")
			protected String volum;
			@XmlElement(name = "VOLEH")
			protected String voleh;
			@XmlElement(name = "GBSTK")
			protected String gbstk;
			@XmlElement(name = "ABSTK")
			protected String abstk;
			@XmlElement(name = "LFGSK")
			protected String lfgsk;
			@XmlElement(name = "LFSTK")
			protected String lfstk;
			@XmlElement(name = "WBSTK")
			protected String wbstk;
			@XmlElement(name = "FKSTK")
			protected String fkstk;
			@XmlElement(name = "FKSAK")
			protected String fksak;
			@XmlElement(name = "BUCHK")
			protected String buchk;
			@XmlElement(name = "KOSTK")
			protected String kostk;
			@XmlElement(name = "LVSTK")
			protected String lvstk;
			@XmlElement(name = "PKSTK")
			protected String pkstk;
			@XmlElement(name = "CMGST")
			protected String cmgst;
			@XmlElement(name = "FSSTK")
			protected String fsstk;
			@XmlElement(name = "LSSTK")
			protected String lsstk;
			@XmlElement(name = "SPSTG")
			protected String spstg;
			@XmlElement(name = "COMPLETENESS")
			protected String completeness;
			@XmlElement(name = "MATERIAL")
			protected String material;
			@XmlElement(name = "SITE")
			protected String site;
			@XmlElement(name = "REASONCODE")
			protected String reasoncode;
			@XmlElement(name = "ORDREASON")
			protected String ordreason;
			@XmlElement(name = "REJREASON")
			protected String rejreason;
			@XmlElement(name = "AUDAT")
			protected String audat;
			@XmlElement(name = "AUART")
			protected String auart;
			@XmlElement(name = "LIFSK")
			protected String lifsk;
			@XmlElement(name = "LIFSP")
			protected String lifsp;
			@XmlElement(name = "ZMEINS")
			protected String zmeins;
			@XmlElement(name = "LGORT")
			protected String lgort;
			@XmlElement(name = "PSTYV")
			protected String pstyv;
			@XmlElement(name = "LFART")
			protected String lfart;
			@XmlElement(name = "ERDAT_DEL")
			protected String erdatdel;
			@XmlElement(name = "ERNAM_DEL")
			protected String ernamdel;
			@XmlElement(name = "WADAT_PGI")
			protected String wadatpgi;
			@XmlElement(name = "WADAT_PGR")
			protected String wadatpgr;
			@XmlElement(name = "FKDAT")
			protected String fkdat;
			@XmlElement(name = "FKART")
			protected String fkart;
			@XmlElement(name = "NETWR")
			protected String netwr;
			@XmlElement(name = "ORD_STAT")
			protected String ordstat;
			@XmlElement(name = "LSP_NOR")
			protected String lspnor;
			@XmlElement(name = "LSP_NAME")
			protected String lspname;
			@XmlElement(name = "LSP_UPD_DESCR")
			protected String lspupddescr;
			@XmlAttribute(name = "SEGMENT", required = true)
			protected String segment;

			/**
			 * Gets the value of the mandt property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMANDT() {
				return mandt;
			}

			/**
			 * Sets the value of the mandt property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMANDT(String value) {
				this.mandt = value;
			}

			/**
			 * Gets the value of the sovbeln property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSOVBELN() {
				return sovbeln;
			}

			/**
			 * Sets the value of the sovbeln property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSOVBELN(String value) {
				this.sovbeln = value;
			}

			/**
			 * Gets the value of the soposnr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSOPOSNR() {
				return soposnr;
			}

			/**
			 * Sets the value of the soposnr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSOPOSNR(String value) {
				this.soposnr = value;
			}

			/**
			 * Gets the value of the revbeln property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREVBELN() {
				return revbeln;
			}

			/**
			 * Sets the value of the revbeln property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREVBELN(String value) {
				this.revbeln = value;
			}

			/**
			 * Gets the value of the reposnr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREPOSNR() {
				return reposnr;
			}

			/**
			 * Sets the value of the reposnr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREPOSNR(String value) {
				this.reposnr = value;
			}

			/**
			 * Gets the value of the suvbeln property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSUVBELN() {
				return suvbeln;
			}

			/**
			 * Sets the value of the suvbeln property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSUVBELN(String value) {
				this.suvbeln = value;
			}

			/**
			 * Gets the value of the suposnr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSUPOSNR() {
				return suposnr;
			}

			/**
			 * Sets the value of the suposnr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSUPOSNR(String value) {
				this.suposnr = value;
			}

			/**
			 * Gets the value of the vbelv property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVBELV() {
				return vbelv;
			}

			/**
			 * Sets the value of the vbelv property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVBELV(String value) {
				this.vbelv = value;
			}

			/**
			 * Gets the value of the posnv property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPOSNV() {
				return posnv;
			}

			/**
			 * Sets the value of the posnv property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPOSNV(String value) {
				this.posnv = value;
			}

			/**
			 * Gets the value of the vbeln property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVBELN() {
				return vbeln;
			}

			/**
			 * Sets the value of the vbeln property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVBELN(String value) {
				this.vbeln = value;
			}

			/**
			 * Gets the value of the posnn property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPOSNN() {
				return posnn;
			}

			/**
			 * Sets the value of the posnn property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPOSNN(String value) {
				this.posnn = value;
			}

			/**
			 * Gets the value of the vbtypn property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVBTYPN() {
				return vbtypn;
			}

			/**
			 * Sets the value of the vbtypn property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVBTYPN(String value) {
				this.vbtypn = value;
			}

			/**
			 * Gets the value of the rfmng property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRFMNG() {
				return rfmng;
			}

			/**
			 * Sets the value of the rfmng property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRFMNG(String value) {
				this.rfmng = value;
			}

			/**
			 * Gets the value of the meins property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMEINS() {
				return meins;
			}

			/**
			 * Sets the value of the meins property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMEINS(String value) {
				this.meins = value;
			}

			/**
			 * Gets the value of the rfwrt property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRFWRT() {
				return rfwrt;
			}

			/**
			 * Sets the value of the rfwrt property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRFWRT(String value) {
				this.rfwrt = value;
			}

			/**
			 * Gets the value of the waers property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getWAERS() {
				return waers;
			}

			/**
			 * Sets the value of the waers property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setWAERS(String value) {
				this.waers = value;
			}

			/**
			 * Gets the value of the bwart property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getBWART() {
				return bwart;
			}

			/**
			 * Sets the value of the bwart property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setBWART(String value) {
				this.bwart = value;
			}

			/**
			 * Gets the value of the matnr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMATNR() {
				return matnr;
			}

			/**
			 * Sets the value of the matnr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMATNR(String value) {
				this.matnr = value;
			}

			/**
			 * Gets the value of the erzet property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getERZET() {
				return erzet;
			}

			/**
			 * Sets the value of the erzet property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setERZET(String value) {
				this.erzet = value;
			}

			/**
			 * Gets the value of the erdat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getERDAT() {
				return erdat;
			}

			/**
			 * Sets the value of the erdat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setERDAT(String value) {
				this.erdat = value;
			}

			/**
			 * Gets the value of the taqui property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getTAQUI() {
				return taqui;
			}

			/**
			 * Sets the value of the taqui property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setTAQUI(String value) {
				this.taqui = value;
			}

			/**
			 * Gets the value of the plmin property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPLMIN() {
				return plmin;
			}

			/**
			 * Sets the value of the plmin property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPLMIN(String value) {
				this.plmin = value;
			}

			/**
			 * Gets the value of the vbtypv property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVBTYPV() {
				return vbtypv;
			}

			/**
			 * Sets the value of the vbtypv property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVBTYPV(String value) {
				this.vbtypv = value;
			}

			/**
			 * Gets the value of the aedat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getAEDAT() {
				return aedat;
			}

			/**
			 * Sets the value of the aedat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setAEDAT(String value) {
				this.aedat = value;
			}

			/**
			 * Gets the value of the fktyp property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFKTYP() {
				return fktyp;
			}

			/**
			 * Sets the value of the fktyp property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFKTYP(String value) {
				this.fktyp = value;
			}

			/**
			 * Gets the value of the brgew property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getBRGEW() {
				return brgew;
			}

			/**
			 * Sets the value of the brgew property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setBRGEW(String value) {
				this.brgew = value;
			}

			/**
			 * Gets the value of the gewei property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getGEWEI() {
				return gewei;
			}

			/**
			 * Sets the value of the gewei property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setGEWEI(String value) {
				this.gewei = value;
			}

			/**
			 * Gets the value of the volum property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVOLUM() {
				return volum;
			}

			/**
			 * Sets the value of the volum property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVOLUM(String value) {
				this.volum = value;
			}

			/**
			 * Gets the value of the voleh property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVOLEH() {
				return voleh;
			}

			/**
			 * Sets the value of the voleh property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVOLEH(String value) {
				this.voleh = value;
			}

			/**
			 * Gets the value of the gbstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getGBSTK() {
				return gbstk;
			}

			/**
			 * Sets the value of the gbstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setGBSTK(String value) {
				this.gbstk = value;
			}

			/**
			 * Gets the value of the abstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getABSTK() {
				return abstk;
			}

			/**
			 * Sets the value of the abstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setABSTK(String value) {
				this.abstk = value;
			}

			/**
			 * Gets the value of the lfgsk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLFGSK() {
				return lfgsk;
			}

			/**
			 * Sets the value of the lfgsk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLFGSK(String value) {
				this.lfgsk = value;
			}

			/**
			 * Gets the value of the lfstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLFSTK() {
				return lfstk;
			}

			/**
			 * Sets the value of the lfstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLFSTK(String value) {
				this.lfstk = value;
			}

			/**
			 * Gets the value of the wbstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getWBSTK() {
				return wbstk;
			}

			/**
			 * Sets the value of the wbstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setWBSTK(String value) {
				this.wbstk = value;
			}

			/**
			 * Gets the value of the fkstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFKSTK() {
				return fkstk;
			}

			/**
			 * Sets the value of the fkstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFKSTK(String value) {
				this.fkstk = value;
			}

			/**
			 * Gets the value of the fksak property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFKSAK() {
				return fksak;
			}

			/**
			 * Sets the value of the fksak property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFKSAK(String value) {
				this.fksak = value;
			}

			/**
			 * Gets the value of the buchk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getBUCHK() {
				return buchk;
			}

			/**
			 * Sets the value of the buchk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setBUCHK(String value) {
				this.buchk = value;
			}

			/**
			 * Gets the value of the kostk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getKOSTK() {
				return kostk;
			}

			/**
			 * Sets the value of the kostk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setKOSTK(String value) {
				this.kostk = value;
			}

			/**
			 * Gets the value of the lvstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLVSTK() {
				return lvstk;
			}

			/**
			 * Sets the value of the lvstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLVSTK(String value) {
				this.lvstk = value;
			}

			/**
			 * Gets the value of the pkstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPKSTK() {
				return pkstk;
			}

			/**
			 * Sets the value of the pkstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPKSTK(String value) {
				this.pkstk = value;
			}

			/**
			 * Gets the value of the cmgst property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCMGST() {
				return cmgst;
			}

			/**
			 * Sets the value of the cmgst property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCMGST(String value) {
				this.cmgst = value;
			}

			/**
			 * Gets the value of the fsstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFSSTK() {
				return fsstk;
			}

			/**
			 * Sets the value of the fsstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFSSTK(String value) {
				this.fsstk = value;
			}

			/**
			 * Gets the value of the lsstk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLSSTK() {
				return lsstk;
			}

			/**
			 * Sets the value of the lsstk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLSSTK(String value) {
				this.lsstk = value;
			}

			/**
			 * Gets the value of the spstg property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSPSTG() {
				return spstg;
			}

			/**
			 * Sets the value of the spstg property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSPSTG(String value) {
				this.spstg = value;
			}

			/**
			 * Gets the value of the completeness property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCOMPLETENESS() {
				return completeness;
			}

			/**
			 * Sets the value of the completeness property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCOMPLETENESS(String value) {
				this.completeness = value;
			}

			/**
			 * Gets the value of the material property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMATERIAL() {
				return material;
			}

			/**
			 * Sets the value of the material property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMATERIAL(String value) {
				this.material = value;
			}

			/**
			 * Gets the value of the site property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSITE() {
				return site;
			}

			/**
			 * Sets the value of the site property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSITE(String value) {
				this.site = value;
			}

			/**
			 * Gets the value of the reasoncode property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREASONCODE() {
				return reasoncode;
			}

			/**
			 * Sets the value of the reasoncode property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREASONCODE(String value) {
				this.reasoncode = value;
			}

			/**
			 * Gets the value of the ordreason property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getORDREASON() {
				return ordreason;
			}

			/**
			 * Sets the value of the ordreason property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setORDREASON(String value) {
				this.ordreason = value;
			}

			/**
			 * Gets the value of the rejreason property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getREJREASON() {
				return rejreason;
			}

			/**
			 * Sets the value of the rejreason property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setREJREASON(String value) {
				this.rejreason = value;
			}

			/**
			 * Gets the value of the audat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getAUDAT() {
				return audat;
			}

			/**
			 * Sets the value of the audat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setAUDAT(String value) {
				this.audat = value;
			}

			/**
			 * Gets the value of the auart property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getAUART() {
				return auart;
			}

			/**
			 * Sets the value of the auart property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setAUART(String value) {
				this.auart = value;
			}

			/**
			 * Gets the value of the lifsk property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLIFSK() {
				return lifsk;
			}

			/**
			 * Sets the value of the lifsk property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLIFSK(String value) {
				this.lifsk = value;
			}

			/**
			 * Gets the value of the lifsp property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLIFSP() {
				return lifsp;
			}

			/**
			 * Sets the value of the lifsp property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLIFSP(String value) {
				this.lifsp = value;
			}

			/**
			 * Gets the value of the zmeins property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getZMEINS() {
				return zmeins;
			}

			/**
			 * Sets the value of the zmeins property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setZMEINS(String value) {
				this.zmeins = value;
			}

			/**
			 * Gets the value of the lgort property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLGORT() {
				return lgort;
			}

			/**
			 * Sets the value of the lgort property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLGORT(String value) {
				this.lgort = value;
			}

			/**
			 * Gets the value of the pstyv property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPSTYV() {
				return pstyv;
			}

			/**
			 * Sets the value of the pstyv property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPSTYV(String value) {
				this.pstyv = value;
			}

			/**
			 * Gets the value of the lfart property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLFART() {
				return lfart;
			}

			/**
			 * Sets the value of the lfart property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLFART(String value) {
				this.lfart = value;
			}

			/**
			 * Gets the value of the erdatdel property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getERDATDEL() {
				return erdatdel;
			}

			/**
			 * Sets the value of the erdatdel property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setERDATDEL(String value) {
				this.erdatdel = value;
			}

			/**
			 * Gets the value of the ernamdel property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getERNAMDEL() {
				return ernamdel;
			}

			/**
			 * Sets the value of the ernamdel property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setERNAMDEL(String value) {
				this.ernamdel = value;
			}

			/**
			 * Gets the value of the wadatpgi property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getWADATPGI() {
				return wadatpgi;
			}

			/**
			 * Sets the value of the wadatpgi property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setWADATPGI(String value) {
				this.wadatpgi = value;
			}

			/**
			 * Gets the value of the wadatpgr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getWADATPGR() {
				return wadatpgr;
			}

			/**
			 * Sets the value of the wadatpgr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setWADATPGR(String value) {
				this.wadatpgr = value;
			}

			/**
			 * Gets the value of the fkdat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFKDAT() {
				return fkdat;
			}

			/**
			 * Sets the value of the fkdat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFKDAT(String value) {
				this.fkdat = value;
			}

			/**
			 * Gets the value of the fkart property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFKART() {
				return fkart;
			}

			/**
			 * Sets the value of the fkart property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFKART(String value) {
				this.fkart = value;
			}

			/**
			 * Gets the value of the netwr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getNETWR() {
				return netwr;
			}

			/**
			 * Sets the value of the netwr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setNETWR(String value) {
				this.netwr = value;
			}

			/**
			 * Gets the value of the ordstat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getORDSTAT() {
				return ordstat;
			}

			/**
			 * Sets the value of the ordstat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setORDSTAT(String value) {
				this.ordstat = value;
			}

			/**
			 * Gets the value of the lspnor property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLSPNOR() {
				return lspnor;
			}

			/**
			 * Sets the value of the lspnor property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLSPNOR(String value) {
				this.lspnor = value;
			}

			/**
			 * Gets the value of the lspname property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLSPNAME() {
				return lspname;
			}

			/**
			 * Sets the value of the lspname property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLSPNAME(String value) {
				this.lspname = value;
			}

			/**
			 * Gets the value of the lspupddescr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLSPUPDDESCR() {
				return lspupddescr;
			}

			/**
			 * Sets the value of the lspupddescr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLSPUPDDESCR(String value) {
				this.lspupddescr = value;
			}

			/**
			 * Gets the value of the segment property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSEGMENT() {
				return segment;
			}

			/**
			 * Sets the value of the segment property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSEGMENT(String value) {
				this.segment = value;
			}

		}

	}

}
