package com.fb.platform.promotion.model;

public enum PromotionType {
	GLOBAL,
	ON_PRODUCT,
	ON_CATEGORY,
	ON_USER
	/*BUY_ONE_GET_ONE_FREE, 
	BUY_TWO_GET_ONE_FREE,
	BUY_BUNDLE_GET_BUNDLE_FREE,
	BUY_BUNDLE_GET_CHEAPEST_FREE,
	
	BUY_WORTH_X_GET_BUNDLE_FREE,
	BUY_WORTH_X_GET_BUNDLE_FOR_VALUE,
	GLOBAL_COUPON*/
	
}
